spring:
  application:
    name: project-management-application
  
  datasource:
    url: jdbc:postgresql://localhost:5432/project_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: project-management-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080
  servlet:
    context-path: /api

keycloak:
  auth-server-url: http://localhost:8081/auth
  realm: project-management
  resource: project-management-client
  public-client: true
  bearer-only: true

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    com.projectmanagement: DEBUG 